export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  NAVIGATE: 'NAVIGATE',
  HISTORY_BACK: 'HISTORY_BACK',
  USER_LOADED: 'USER_LOADED',
  GIFTS_LOADED: 'GIFTS_LOADED',
  HISTORY_LOADED: 'HISTORY_LOADED',
  LEADERBOARD_LOADED: 'LEADERBOARD_LOADED',
  TASKS_LOADED: 'TASKS_LOADED',
  GIFT_SELECT: 'GIFT_SELECT',
  MESSAGE: 'MESSAGE'
}
