export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  MENU_SELECT: 'MENU_SELECT',
  GIFTS_LOADED: 'GIFTS_LOADED',
  HISTORY_LOADED: 'HISTORY_LOADED',
  TASKS_LOADED: 'TASKS_LOADED'
}
